name: DeathCounter
version: '1.0-SNAPSHOT'
main: me.harrylesanto.deathcounter.DeathCounter
api-version: 1.21
author: Harry Le Santo
commands:
  deathcounter:
    description: DeathCounter base command.
    usage: /deathcounter
    aliases: [deathcount, deaths, dc]